<template>
  <AdminPasswordGate v-if="needsLogin" @authed="loadAll" />
  <main class="adm-page"><div class="adm-aurora"/><div class="adm-wrap">
    <header class="adm-topbar"><NuxtLink to="/admin" class="adm-btn-ghost"><Icon name="ph:arrow-left-bold"/> Dashboard</NuxtLink><div class="adm-logo"><Icon name="ph:trophy-bold" class="adm-logo-icon"/><span>Torneios</span></div></header>
    <section class="adm-panel"><div class="adm-panel-head"><div><h2><Icon name="ph:trophy-bold"/> Torneios</h2><p>A publicação de um torneio encerra automaticamente o ativo anterior.</p></div><button class="adm-btn-ghost" @click="newTournament">Novo torneio</button></div>
      <div class="form-grid"><label class="wide">Título<input v-model="form.title" maxlength="100" class="adm-input"></label><label class="wide">Descrição<textarea v-model="form.description" maxlength="600" class="adm-input" rows="3"/></label><label>Início<input v-model="form.startsAt" type="datetime-local" class="adm-input"></label><label>Fim<input v-model="form.endsAt" type="datetime-local" class="adm-input"></label><label>Status<select v-model="form.status" class="adm-input"><option value="draft">Rascunho</option><option value="active">Ativo</option><option value="finished">Encerrado</option></select></label><label class="wide">Premiações <small>(uma por linha)</small><textarea v-model="prizesText" class="adm-input" rows="4" placeholder="R$ 1.000&#10;R$ 500&#10;R$ 250"/></label><label class="wide">Regras <small>(uma por linha)</small><textarea v-model="rulesText" class="adm-input" rows="4"/></label><label class="wide">Ranking <small>(Nome | pontos)</small><textarea v-model="rankingText" class="adm-input" rows="6" placeholder="Maria | 9500&#10;Ana | 8700"/></label></div>
      <button class="adm-btn-primary" :disabled="savingTournament" @click="saveTournament"><Icon name="ph:paper-plane-tilt-bold"/> {{ savingTournament?'Salvando...':form.id?'Atualizar torneio':'Criar torneio' }}</button>
      <div class="tournament-list"><button v-for="item in tournaments" :key="item.id" @click="editTournament(item)"><span><strong>{{ item.title }}</strong><small>{{ item.status }} · {{ formatDate(item.endsAt) }}</small></span><Icon name="ph:pencil-simple-bold"/></button></div>
    </section>
    <div v-if="feedback" class="feedback" :class="feedbackType" role="status">{{ feedback }}</div>
  </div></main>
</template>
<script setup lang="ts">
import type { Tournament } from '../../../shared/tournaments'
definePageMeta({middleware:'admin'})
const {adminFetch,needsLogin}=useAdmin()
const tournaments=ref<Tournament[]>([]); const savingTournament=ref(false); const feedback=ref(''); const feedbackType=ref<'ok'|'error'>('ok')
const blank=()=>({id:'',title:'',description:'',startsAt:new Date().toISOString().slice(0,16),endsAt:new Date(Date.now()+7*86400000).toISOString().slice(0,16),status:'draft' as Tournament['status']})
const form=reactive(blank()); const prizesText=ref(''); const rulesText=ref(''); const rankingText=ref('')
const notify=(message:string,type:'ok'|'error'='ok')=>{feedback.value=message;feedbackType.value=type;setTimeout(()=>feedback.value='',3500)}
const loadAll=async()=>{try{tournaments.value=(await adminFetch<{tournaments:Tournament[]}>('/api/admin/tournaments')).tournaments}catch{notify('Não foi possível carregar os torneios.','error')}}
const newTournament=()=>{Object.assign(form,blank());prizesText.value='';rulesText.value='';rankingText.value=''}
const editTournament=(item:Tournament)=>{Object.assign(form,{...item,startsAt:item.startsAt.slice(0,16),endsAt:item.endsAt.slice(0,16)});prizesText.value=item.prizes.map(p=>p.label).join('\n');rulesText.value=item.rules.join('\n');rankingText.value=item.ranking.map(r=>`${r.name} | ${r.score}`).join('\n');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
const saveTournament=async()=>{savingTournament.value=true;try{const body={...form,prizes:prizesText.value.split('\n').filter(Boolean).map((label,i)=>({place:i+1,label:label.trim()})),rules:rulesText.value.split('\n').map(s=>s.trim()).filter(Boolean),ranking:rankingText.value.split('\n').filter(Boolean).map((line,i)=>{const [name,score]=line.split('|');return{position:i+1,name:name?.trim(),score:Number(score)}})};const saved=await adminFetch<Tournament>(form.id?`/api/admin/tournaments/${form.id}`:'/api/admin/tournaments',{method:form.id?'PUT':'POST',body});notify(saved.status==='active'?'Torneio publicado.':'Torneio salvo.');newTournament();await loadAll()}catch(error:any){notify(error?.data?.message||'Não foi possível salvar o torneio.','error')}finally{savingTournament.value=false}}
const formatDate=(v:string)=>new Date(v).toLocaleDateString('pt-BR')
onMounted(()=>{if(!needsLogin.value)loadAll()});useHead({title:'Torneios - Admin'})
</script>
<style>@import "~/assets/css/admin-theme.css";</style>
<style scoped>
.adm-page{min-height:100vh;background:var(--adm-bg);color:var(--adm-text);font-family:Manrope,sans-serif}.adm-wrap{position:relative;z-index:1;max-width:960px;margin:auto;padding:24px;display:grid;gap:22px}.adm-topbar{display:flex;align-items:center;justify-content:space-between}.adm-logo{display:flex;align-items:center;gap:10px;font-weight:800}.adm-logo-icon{color:var(--adm-accent);font-size:24px}.adm-panel{padding:24px;border:1px solid var(--adm-border-soft);border-radius:18px;background:var(--adm-panel)}.adm-panel-head{display:flex;align-items:start;justify-content:space-between;gap:14px;margin-bottom:22px}.adm-panel-head h2{display:flex;align-items:center;gap:8px;margin:0}.adm-panel-head p{color:var(--adm-muted);font-size:13px;margin:5px 0}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px}.form-grid label{display:flex;flex-direction:column;gap:7px;color:var(--adm-muted);font-size:13px;font-weight:700}.form-grid .wide{grid-column:1/-1}.adm-input{width:100%;padding:11px 12px;border:1px solid var(--adm-border-soft);border-radius:10px;background:var(--adm-bg-2);color:var(--adm-text);font:inherit}.color-input{width:100%;height:42px;border:0;border-radius:10px;background:transparent}.check{flex-direction:row!important;align-items:center}.adm-btn-primary,.adm-btn-ghost{display:inline-flex;align-items:center;gap:7px;padding:10px 16px;border-radius:10px;font-weight:700;cursor:pointer;text-decoration:none}.adm-btn-primary{border:0;background:var(--adm-accent);color:#1a0410}.adm-btn-ghost{border:1px solid var(--adm-border);background:var(--adm-panel);color:var(--adm-muted)}.tournament-list{display:grid;gap:8px;margin-top:24px}.tournament-list button{display:flex;justify-content:space-between;align-items:center;padding:14px;border:1px solid var(--adm-border-soft);border-radius:11px;background:var(--adm-bg-2);color:var(--adm-text);text-align:left;cursor:pointer}.tournament-list span{display:flex;flex-direction:column;gap:4px}.tournament-list small{color:var(--adm-muted)}.feedback{position:fixed;right:24px;bottom:24px;padding:14px 18px;border-radius:12px;background:#17241f;border:1px solid #2dd4a7;color:#62d49b}.feedback.error{background:#29161a;border-color:#ff5d6c;color:#ff8994}@media(max-width:620px){.form-grid{grid-template-columns:1fr}.form-grid>*{grid-column:1!important}.adm-topbar{align-items:start;gap:16px;flex-direction:column-reverse}.adm-wrap{padding:16px}.adm-panel{padding:18px}}
</style>
